### ISSUE TITLE
Add RACK_DIR to all firmware makefiles

### ISSUE THREAD

**Issue by suit4** [Dewb/monome-rack#46]
macOS 10.14.5

Rack V1 built from source.

I cloned monome-rack to plugins directory.
``make`` fails building firmware files, as ${RACK_DIR}/arch.mk cannot be found.

I had to add 
``RACK_DIR ?= ../../..``
to all firmware/*.mk files to fix this.

**Comment by Dewb** [comment]
RACK_DIR isn't specified in the firmware makefiles because the correct path is different for Rack SDK builds vs. the full Rack source. RACK_DIR needs to be set when you call `make`, either on the command line or in the environment. Apologies, this was missing in the Rack source build instructions, I just fixed it. Thanks for the report!
