### ISSUE TITLE
Teletype (1.0.0-pre) registers rise and fall of pulse on trigger inputs

### ISSUE THREAD

**Issue by Funk-Burasuta** [Dewb/monome-rack#50]
### What operating system and version are you running?
Windows 10 x64

### What version of Rack are you running?
Rack 1.1.6

### What's the behavior you observed?
I begin by initializing some things, like O maximum and pattern length on live mode:
`PN.END 0 7`
`O.MAX 7`

So, I type in a script on teletype that addresses pattern 0 and returns a pulse on 1, for instance:
`PN.I 0 O`
`CV 1 N PN.HERE 0`
`TR.PULSE 1`

The thing that happens is that when this script is called, it's called twice per pulse cycle. With a square wave you can see it advancing at double the tempo when you go to the pattern table screen. When varying the incoming pulse width you can also see that it offsets every other script call off the initial cycle tempo.

I am out of the loop when it comes to whether the real Teletype did this, but it sure doesn't sound like it does.

**Comment by Dewb** [comment]
Hi @Funk-Burasuta, thanks for being willing to try this out during development! You're absolutely right that this is not the expected behavior; the VCV-specific code was triggering scripts on both the rising and falling edge of the input signals. 

A fixed experimental Windows build should be available on the releases page, Mac will follow in a few minutes.
