### ISSUE TITLE
Support for Non-US keyboards in Teletype

### ISSUE THREAD

**Issue by jpnielsen** [Dewb/monome-rack#84]
### What operating system and version are you running?
Windows 11

### What version of Rack are you running?
Rack 2.0.4 pre-release

### What's the behavior you observed?
My DK keyboard is not mapped correctly in Teletype.
_ on my KBD is ? in teletype.
- on my KBD is / in teletype.
? on my KBD is _ in teletype.

etc.

### What should have happened instead?

The keyboard should be mapped correctly, (like in VCV Fundamental Notes)

http://kbdlayout.info/KBDDA/

**Comment by Dewb** [comment]
Can you try this build and let me know how it works for you? https://github.com/Dewb/monome-rack/actions/runs/1599525521

I initially added international keyboard support (based on Rack 2.0's interpretation of int'l support, which appears to be limited to printable characters) to alpha5, but I got feedback from an ES keyboard user that they strongly preferred the previous behavior of assuming en-US layout (which is what the hardware module does.)

This probably needs to be a switchable option, but I want to understand the user needs a bit more so the configurable behavior actually solves people's problems.

**Comment by jpnielsen** [comment]
"[" and "]" dont work - On my keyboard they are right-alt 8 and 9
"?" don't work - on my KBD it's shif and the key three keys left of backspace.

Just keep US mapping -it's no biggie - i will just print the keymap and note what keys they are on a DK keyboard.

**Comment by vanicat** [comment]
This problem could stop me from using this module: I found it very difficult to not use my keyboard configuration.
That said, I can completely understand this is not your priority, and I could also print the en-us layout and use the it. But it will slow me.

**Comment by iacs** [comment]
I came here to report this issue as well.
Currently, it's extremely cumbersome to use this module when it assumes you have an american layout, which most people outside of the US don't.

It would be great to see an update that respected the system's keyboard layout, since this looks like a very deep module

**Comment by Dewb** [comment]
Absolutely, this is top priority for an update. Unfortunately, given the way the firmware works, changes are needed to both the VCV and the firmware side to make keystroke assignment more flexible. It might make sense to go all the way and add international support to both the hardware and software at the same time. Which is good, it will help both VCV and hardware users, but it means a bit more work.

(Some technical background: USB keyboards do not have a built-in locale; they unfortunately all return the same scancodes based on the default US layout. Interpretation is left up to the operating system. The Teletype firmware does not have an operating system, so it acts directly on the scancodes. We essentially need to add that OS translation layer into the hardware. The VCV Rack version *does* have the OS translation layer, but it also has the GLFW abstraction layer and Rack's own international translation tools, which help in some ways but make the problem of supporting both environments harder.)

**Comment by Dewb** [comment]
That's a good approach for a workaround -- you should be able to do this in your favorite text editor, and then right-click Teletype and choose **Import scenes > Active scene > Paste and merge clipboard into current scene**. You'll need to observe the limits of the Teletype text import format -- keep lines under 30-31 characters, and prefix each clipboard paste with which script you want it to go into.  So you could write

```
# M
TR.P 1
L 1 4: CV I P - I 1
```

in your text editor, and then paste that to popular the M script.

**Comment by Dewb** [comment]
I started thinking about possible strategies to automate the workaround as you describe, but I think it makes much more sense to apply that energy towards proper international support rather than workarounds. I still think supporting in both hardware & software is the long-term goal, but I think we can get some form of VCV Rack-only international support in place as a stepping-stone. What keyboard locale are you using, and are you willing to beta test a custom keyboard map feature?

**Comment by jpnielsen** [comment]
I have ordered a US keyboard, the issue is solved for me.

**Comment by Dewb** [comment]
The GLFW to HID mapping is now data-driven rather than hardcoded. You can define custom layout/maps by authoring JSON files. Details are here: https://github.com/Dewb/monome-rack/tree/main/res/keymaps

This seems sufficient to create, as examples, US Dvorak and UK/GB standard layouts. I think it should also be enough to cover the [Danish Windows layout](http://kbdlayout.info/KBDDA/) mentioned by @jpnielsen. I'm a little less clear on whether this is enough flexibility to make a good layout for the Mac JIS keyboard; I can set my US Mac to Japanese layout, but it doesn't seem to match the behavior of an actual JIS hardware layout.

Does this system, and the instructions linked above, make sense? If anyone is willing to try it out and let me know if it covers your layout needs, I'd appreciate it. It's probably not a good idea for me to guess at international layouts without the ability to try them myself, but I will happily merge additional layouts that folks are able to create and test.
